name: release

on:
  release:
    types: 
      - published

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    uses: ./.github/workflows/build.yml

  upload-release-assets:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: AsyncTextureLoad
          path: AsyncTextureLoad
      - uses: actions/download-artifact@v4
        with:
          name: AsyncTextureLoad.version
      - run: tree

      - name: Create Zip
        run: |
          cd AsyncTextureLoad
          zip -r9 ../AsyncTextureLoad.zip *

      - name: Upload Release Assets
        run: |
          gh release upload --clobber ${{ github.ref_name }}  \
            AsyncTextureLoad.zip                  \
            AsyncTextureLoad.version
